/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import logica.LogicaResolucion;

/**
 *
 * @author usuario
 */
public class InterfazPuzzle extends javax.swing.JFrame
{

    /**
     * Creates new form InterfazPuzzle
     */
    public InterfazPuzzle()
    {
        initComponents();

        solucion = new LogicaResolucion(jTxtSolucion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPnlSolucion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtSolucion = new javax.swing.JTextArea();
        jPnlOpciones = new javax.swing.JPanel();
        jPnlCF = new javax.swing.JPanel();
        jTxtCF1 = new javax.swing.JTextField();
        jTxtCF2 = new javax.swing.JTextField();
        jTxtCF3 = new javax.swing.JTextField();
        jTxtCF4 = new javax.swing.JTextField();
        jTxtCF5 = new javax.swing.JTextField();
        jTxtCF6 = new javax.swing.JTextField();
        jTxtCF7 = new javax.swing.JTextField();
        jTxtCF8 = new javax.swing.JTextField();
        jTxtCF9 = new javax.swing.JTextField();
        jPnlCI = new javax.swing.JPanel();
        jTxtCI1 = new javax.swing.JTextField();
        jTxtCI2 = new javax.swing.JTextField();
        jTxtCI3 = new javax.swing.JTextField();
        jTxtCI4 = new javax.swing.JTextField();
        jTxtCI5 = new javax.swing.JTextField();
        jTxtCI6 = new javax.swing.JTextField();
        jTxtCI7 = new javax.swing.JTextField();
        jTxtCI8 = new javax.swing.JTextField();
        jTxtCI0 = new javax.swing.JTextField();
        jPnlMetodos = new javax.swing.JPanel();
        jCmbMetodos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IAR-Puzzle");
        setName("frm_Interfaz"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPnlSolucion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTxtSolucion.setEditable(false);
        jTxtSolucion.setColumns(20);
        jTxtSolucion.setRows(5);
        jScrollPane1.setViewportView(jTxtSolucion);

        javax.swing.GroupLayout jPnlSolucionLayout = new javax.swing.GroupLayout(jPnlSolucion);
        jPnlSolucion.setLayout(jPnlSolucionLayout);
        jPnlSolucionLayout.setHorizontalGroup(
            jPnlSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlSolucionLayout.setVerticalGroup(
            jPnlSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPnlOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPnlCF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuración Final"));

        jTxtCF1.setText("1");
        jTxtCF1.setToolTipText("");

        jTxtCF2.setText("2");

        jTxtCF3.setText("3");

        jTxtCF4.setText("4");

        jTxtCF5.setText("5");
        jTxtCF5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtCF5ActionPerformed(evt);
            }
        });

        jTxtCF6.setText("6");

        jTxtCF7.setText("7");

        jTxtCF8.setText("8");

        jTxtCF9.setText("0");

        javax.swing.GroupLayout jPnlCFLayout = new javax.swing.GroupLayout(jPnlCF);
        jPnlCF.setLayout(jPnlCFLayout);
        jPnlCFLayout.setHorizontalGroup(
            jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCFLayout.createSequentialGroup()
                        .addComponent(jTxtCF7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCFLayout.createSequentialGroup()
                        .addComponent(jTxtCF4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCFLayout.createSequentialGroup()
                        .addComponent(jTxtCF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPnlCFLayout.setVerticalGroup(
            jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCFLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPnlCI.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuración Inicial"));

        jTxtCI1.setText("1");

        jTxtCI2.setText("2");
        jTxtCI2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtCI2ActionPerformed(evt);
            }
        });

        jTxtCI3.setText("3");

        jTxtCI4.setText("0");

        jTxtCI5.setText("5");

        jTxtCI6.setText("6");

        jTxtCI7.setText("4");

        jTxtCI8.setText("7");

        jTxtCI0.setText("8");

        javax.swing.GroupLayout jPnlCILayout = new javax.swing.GroupLayout(jPnlCI);
        jPnlCI.setLayout(jPnlCILayout);
        jPnlCILayout.setHorizontalGroup(
            jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCILayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCILayout.createSequentialGroup()
                        .addComponent(jTxtCI7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCILayout.createSequentialGroup()
                        .addComponent(jTxtCI4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCILayout.createSequentialGroup()
                        .addComponent(jTxtCI1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPnlCILayout.setVerticalGroup(
            jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCILayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCI6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCI7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCI8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCI0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPnlMetodos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Método de Resolución"));

        jCmbMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero en Anchura", "Primero en Profundidad", "Primero el Mejor", "A*" }));
        jCmbMetodos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbMetodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlMetodosLayout = new javax.swing.GroupLayout(jPnlMetodos);
        jPnlMetodos.setLayout(jPnlMetodosLayout);
        jPnlMetodosLayout.setHorizontalGroup(
            jPnlMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbMetodos, 0, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlMetodosLayout.setVerticalGroup(
            jPnlMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlOpcionesLayout = new javax.swing.GroupLayout(jPnlOpciones);
        jPnlOpciones.setLayout(jPnlOpcionesLayout);
        jPnlOpcionesLayout.setHorizontalGroup(
            jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlOpcionesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlOpcionesLayout.createSequentialGroup()
                        .addComponent(jPnlCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPnlCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPnlOpcionesLayout.setVerticalGroup(
            jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlOpcionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlSolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        solucion.agregarTexto("************************************************");
        solucion.agregarTexto("                   PUZZLE IAR                   ");
        solucion.agregarTexto("************************************************");
        solucion.agregarTexto("Caracterisitcas del Juego:");
        solucion.agregarTexto("-Solo se permite ingresar valores del 0-8");
        solucion.agregarTexto("-Al valor 0 se lo considera como Espacio/Comodín");
        solucion.agregarTexto("*************************************************");

    }//GEN-LAST:event_formWindowOpened

    private void jTxtCI2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtCI2ActionPerformed
    {//GEN-HEADEREND:event_jTxtCI2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCI2ActionPerformed

    private void jTxtCF5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtCF5ActionPerformed
    {//GEN-HEADEREND:event_jTxtCF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCF5ActionPerformed

    private void jCmbMetodosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbMetodosActionPerformed
    {//GEN-HEADEREND:event_jCmbMetodosActionPerformed
        int i = jCmbMetodos.getSelectedIndex();

        switch (i)
        {
            case 0:
                solucion.agregarTexto("Primero en Anchura");
                break;

            case 1:
                solucion.agregarTexto("Primero en Profundidad");
                break;
            case 2:
                solucion.agregarTexto("Primero el Mejor");
                break;
            case 3:
                solucion.agregarTexto("A*");
                break;

        }
    }//GEN-LAST:event_jCmbMetodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new InterfazPuzzle().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCmbMetodos;
    private javax.swing.JPanel jPnlCF;
    private javax.swing.JPanel jPnlCI;
    private javax.swing.JPanel jPnlMetodos;
    private javax.swing.JPanel jPnlOpciones;
    private javax.swing.JPanel jPnlSolucion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCF1;
    private javax.swing.JTextField jTxtCF2;
    private javax.swing.JTextField jTxtCF3;
    private javax.swing.JTextField jTxtCF4;
    private javax.swing.JTextField jTxtCF5;
    private javax.swing.JTextField jTxtCF6;
    private javax.swing.JTextField jTxtCF7;
    private javax.swing.JTextField jTxtCF8;
    private javax.swing.JTextField jTxtCF9;
    private javax.swing.JTextField jTxtCI0;
    private javax.swing.JTextField jTxtCI1;
    private javax.swing.JTextField jTxtCI2;
    private javax.swing.JTextField jTxtCI3;
    private javax.swing.JTextField jTxtCI4;
    private javax.swing.JTextField jTxtCI5;
    private javax.swing.JTextField jTxtCI6;
    private javax.swing.JTextField jTxtCI7;
    private javax.swing.JTextField jTxtCI8;
    private javax.swing.JTextArea jTxtSolucion;
    // End of variables declaration//GEN-END:variables
LogicaResolucion solucion;
}
