/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Font;
import logica.LogicaResolucion;
import soporte.Nodo;

/**
 *
 * @author usuario
 */
public class InterfazPuzzle extends javax.swing.JFrame
{

    /**
     * Creates new form InterfazPuzzle
     */
    public InterfazPuzzle()
    {
        initComponents();

        solucion = new LogicaResolucion(jTxtSolucion);

        introduccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPnlSolucion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtSolucion = new javax.swing.JTextArea();
        jPnlOpciones = new javax.swing.JPanel();
        jPnlCF = new javax.swing.JPanel();
        jTxtCF1 = new javax.swing.JTextField();
        jTxtCF2 = new javax.swing.JTextField();
        jTxtCF3 = new javax.swing.JTextField();
        jTxtCF4 = new javax.swing.JTextField();
        jTxtCF5 = new javax.swing.JTextField();
        jTxtCF6 = new javax.swing.JTextField();
        jTxtCF7 = new javax.swing.JTextField();
        jTxtCF8 = new javax.swing.JTextField();
        jTxtCF9 = new javax.swing.JTextField();
        jPnlCI = new javax.swing.JPanel();
        jTxtCI1 = new javax.swing.JTextField();
        jTxtCI2 = new javax.swing.JTextField();
        jTxtCI3 = new javax.swing.JTextField();
        jTxtCI4 = new javax.swing.JTextField();
        jTxtCI5 = new javax.swing.JTextField();
        jTxtCI6 = new javax.swing.JTextField();
        jTxtCI7 = new javax.swing.JTextField();
        jTxtCI8 = new javax.swing.JTextField();
        jTxtCI9 = new javax.swing.JTextField();
        jPnlMetodos = new javax.swing.JPanel();
        jCmbMetodos = new javax.swing.JComboBox<>();
        jPnlParam = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtProfMax = new javax.swing.JTextField();
        jTxtCantMaxExplorar = new javax.swing.JTextField();
        jPnlBotones = new javax.swing.JPanel();
        jBtnResolver = new javax.swing.JButton();
        jBtnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IAR-Puzzle");
        setName("frm_Interfaz"); // NOI18N

        jPnlSolucion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTxtSolucion.setEditable(false);
        jTxtSolucion.setColumns(20);
        jTxtSolucion.setRows(5);
        jScrollPane1.setViewportView(jTxtSolucion);
        jTxtSolucion.setFont(fuente);

        javax.swing.GroupLayout jPnlSolucionLayout = new javax.swing.GroupLayout(jPnlSolucion);
        jPnlSolucion.setLayout(jPnlSolucionLayout);
        jPnlSolucionLayout.setHorizontalGroup(
            jPnlSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlSolucionLayout.setVerticalGroup(
            jPnlSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPnlOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPnlCF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuración Final"));

        jTxtCF1.setText("1");
        jTxtCF1.setToolTipText("");

        jTxtCF2.setText("2");

        jTxtCF3.setText("3");

        jTxtCF4.setText("4");

        jTxtCF5.setText("5");

        jTxtCF6.setText("6");

        jTxtCF7.setText("7");

        jTxtCF8.setText("8");

        jTxtCF9.setText("0");

        javax.swing.GroupLayout jPnlCFLayout = new javax.swing.GroupLayout(jPnlCF);
        jPnlCF.setLayout(jPnlCFLayout);
        jPnlCFLayout.setHorizontalGroup(
            jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCFLayout.createSequentialGroup()
                        .addComponent(jTxtCF7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jPnlCFLayout.createSequentialGroup()
                        .addComponent(jTxtCF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF6))
                    .addGroup(jPnlCFLayout.createSequentialGroup()
                        .addComponent(jTxtCF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCF3)))
                .addGap(36, 36, 36))
        );
        jPnlCFLayout.setVerticalGroup(
            jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCFLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCF1)
                    .addComponent(jTxtCF2)
                    .addComponent(jTxtCF3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCF4)
                    .addComponent(jTxtCF5)
                    .addComponent(jTxtCF6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCF7)
                    .addComponent(jTxtCF8)
                    .addComponent(jTxtCF9))
                .addGap(19, 19, 19))
        );

        confFinalArray[0][0]=jTxtCF1;
        confFinalArray[0][1]=jTxtCF2;
        confFinalArray[0][2]=jTxtCF3;
        confFinalArray[1][0]=jTxtCF4;
        confFinalArray[1][1]=jTxtCF5;
        confFinalArray[1][2]=jTxtCF6;
        confFinalArray[2][0]=jTxtCF7;
        confFinalArray[2][1]=jTxtCF8;
        confFinalArray[2][2]=jTxtCF9;

        jPnlCI.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuración Inicial"));

        jTxtCI1.setText("1");

        jTxtCI2.setText("2");

        jTxtCI3.setText("3");

        jTxtCI4.setText("0");

        jTxtCI5.setText("5");

        jTxtCI6.setText("6");

        jTxtCI7.setText("4");

        jTxtCI8.setText("7");

        jTxtCI9.setText("8");

        javax.swing.GroupLayout jPnlCILayout = new javax.swing.GroupLayout(jPnlCI);
        jPnlCI.setLayout(jPnlCILayout);
        jPnlCILayout.setHorizontalGroup(
            jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCILayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCILayout.createSequentialGroup()
                        .addComponent(jTxtCI7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jPnlCILayout.createSequentialGroup()
                        .addComponent(jTxtCI4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI6))
                    .addGroup(jPnlCILayout.createSequentialGroup()
                        .addComponent(jTxtCI1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCI3)))
                .addGap(35, 35, 35))
        );
        jPnlCILayout.setVerticalGroup(
            jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCILayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCI1)
                    .addComponent(jTxtCI2)
                    .addComponent(jTxtCI3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCI4)
                    .addComponent(jTxtCI5)
                    .addComponent(jTxtCI6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCI7)
                    .addComponent(jTxtCI8)
                    .addComponent(jTxtCI9))
                .addGap(19, 19, 19))
        );

        confInicialArray[0][0]=jTxtCI1;
        confInicialArray[0][1]=jTxtCI2;
        confInicialArray[0][2]=jTxtCI3;
        confInicialArray[1][0]=jTxtCI4;
        confInicialArray[1][1]=jTxtCI5;
        confInicialArray[1][2]=jTxtCI6;
        confInicialArray[2][0]=jTxtCI7;
        confInicialArray[2][1]=jTxtCI8;
        confInicialArray[2][2]=jTxtCI9;

        jPnlMetodos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Método de Resolución"));

        jCmbMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero en Anchura", "Primero en Profundidad", "Primero el Mejor", "A*" }));
        jCmbMetodos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbMetodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlMetodosLayout = new javax.swing.GroupLayout(jPnlMetodos);
        jPnlMetodos.setLayout(jPnlMetodosLayout);
        jPnlMetodosLayout.setHorizontalGroup(
            jPnlMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbMetodos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlMetodosLayout.setVerticalGroup(
            jPnlMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnlParam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Parámetros"));

        jLabel1.setText("Profundidad MAXIMA:");

        jLabel2.setText("Cantidad MAXIMA de Nodos Explorar:");

        jTxtProfMax.setText("4");

        jTxtCantMaxExplorar.setText("100");

        javax.swing.GroupLayout jPnlParamLayout = new javax.swing.GroupLayout(jPnlParam);
        jPnlParam.setLayout(jPnlParamLayout);
        jPnlParamLayout.setHorizontalGroup(
            jPnlParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlParamLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtProfMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlParamLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtCantMaxExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlParamLayout.setVerticalGroup(
            jPnlParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtProfMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPnlParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtCantMaxExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jPnlBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jBtnResolver.setText("Resolver");
        jBtnResolver.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnResolverMouseClicked(evt);
            }
        });

        jBtnReiniciar.setText("Reiniciar");
        jBtnReiniciar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jBtnReiniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotonesLayout = new javax.swing.GroupLayout(jPnlBotones);
        jPnlBotones.setLayout(jPnlBotonesLayout);
        jPnlBotonesLayout.setHorizontalGroup(
            jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnResolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlBotonesLayout.setVerticalGroup(
            jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotonesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnResolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnlOpcionesLayout = new javax.swing.GroupLayout(jPnlOpciones);
        jPnlOpciones.setLayout(jPnlOpcionesLayout);
        jPnlOpcionesLayout.setHorizontalGroup(
            jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlMetodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlOpcionesLayout.createSequentialGroup()
                        .addComponent(jPnlCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnlCF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPnlOpcionesLayout.setVerticalGroup(
            jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlOpcionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlCF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlSolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlSolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void introduccion()
    {
        // TODO add your handling code here:
        solucion.agregarTexto("************************************************");
        solucion.agregarTexto("                   PUZZLE IAR                   ");
        solucion.agregarTexto("************************************************");
        solucion.agregarTexto("Caracterisitcas del Juego:");
        solucion.agregarTexto("-Solo se permite ingresar valores del 0-8");
        solucion.agregarTexto("-Al valor 0 se lo considera como Espacio/Comodín");
        solucion.agregarTexto("*************************************************");

    }

    private int[][] obtenerConfInicial()
    {
        int[][] confInicial = new int[3][3];

        for (int i = 0; i < 3; i++)
        {
            for (int j = 0; j < 3; j++)
            {
                confInicial[i][j] = Integer.parseInt(confInicialArray[i][j].getText());
            }
        }

        return confInicial;
    }

    private int[][] obtenerConfFinal()
    {
        int[][] confFinal = new int[3][3];

        for (int i = 0; i < 3; i++)
        {
            for (int j = 0; j < 3; j++)
            {
                confFinal[i][j] = Integer.parseInt(confFinalArray[i][j].getText());
            }
        }

        return confFinal;
    }

    private void jCmbMetodosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbMetodosActionPerformed
    {//GEN-HEADEREND:event_jCmbMetodosActionPerformed

    }//GEN-LAST:event_jCmbMetodosActionPerformed

    private void jBtnReiniciarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnReiniciarMouseClicked
    {//GEN-HEADEREND:event_jBtnReiniciarMouseClicked
        jTxtSolucion.setText("");

        introduccion();
    }//GEN-LAST:event_jBtnReiniciarMouseClicked

    private void jBtnResolverMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnResolverMouseClicked
    {//GEN-HEADEREND:event_jBtnResolverMouseClicked
        int[][] confInicial = obtenerConfInicial();
        int[][] confFinal = obtenerConfFinal();
        int profMAx = Integer.parseInt(jTxtProfMax.getText());
        int cantMaxExplorar = Integer.parseInt(jTxtCantMaxExplorar.getText());
        int fila = 3, columna = 3, profundidad = 0;
        double SinLimites = 0;
        solucion.configurar(confInicial, confFinal, profMAx, cantMaxExplorar);

        Nodo nodoRaiz;
        Nodo resultado;

        int index = jCmbMetodos.getSelectedIndex();

        switch (index)
        {
            case 0:
                //lo primero que necesitamos hacer para buscar la solucion es convertir el 
                //array ConfInicial en un nodo el cual sera el nodo origen (el primero)      
                nodoRaiz = new Nodo(confInicial);
                solucion.agregarTexto("---------Paso Por Paso----------");
                resultado = solucion.buscarSolucionAnchura(nodoRaiz, confFinal, profMAx, cantMaxExplorar);
                if (resultado == null)
                {
                    solucion.agregarTexto("NO SE ENCONTRO SOLUCION DENTRO DE LOS LIMITES ESTABLECIDOS");
                } else
                {
                    solucion.agregarTexto("--------EL CAMINO A LA SOLUCION ES------------ ");
                    while (resultado.getPadre() != null)
                    {
                        solucion.imprimirSolucion(resultado.getEstado());
                        resultado = resultado.getPadre();
                    }
                    solucion.agregarTexto("Nodo inicial:");
                    for (int i = 0; i < fila; i++)
                    {
                        for (int j = 0; j < columna; j++)
                        {
                            solucion.agregarTextoMatriz("[" + confInicial[i][j] + "]");
                        }
                        solucion.agregarTexto("");
                    }
                }
//                solucion.agregarTexto("Primero en Anchura");
                break;

            case 1:
                nodoRaiz = new Nodo(confInicial);
                solucion.agregarTexto("---------Paso Por Paso----------");
                resultado = solucion.buscarSolucionProfundidad(nodoRaiz, confFinal, profMAx, cantMaxExplorar);
                if (resultado == null)
                {
                    solucion.agregarTexto("NO SE ENCONTRO SOLUCION DENTRO DE LOS LIMITES ESTABLECIDOS");
                } else
                {
                    solucion.agregarTexto("--------EL CAMINO A LA SOLUCION ES------------ ");
                    while (resultado.getPadre() != null)
                    {
                        solucion.imprimirSolucion(resultado.getEstado());
                        resultado = resultado.getPadre();
                    }
                    solucion.agregarTexto("Nodo inicial:");
                    for (int i = 0; i < fila; i++)
                    {
                        for (int j = 0; j < columna; j++)
                        {
                            solucion.agregarTextoMatriz("[" + confInicial[i][j] + "]");
                        }
                        solucion.agregarTexto("");
                    }
                }
//                solucion.agregarTexto("Primero en Profundidad");
                break;
            case 2:
                nodoRaiz = new Nodo(confInicial);
                solucion.agregarTexto("---------Paso Por Paso----------");
                resultado = solucion.buscarSolucionPrimeroElMejor(nodoRaiz, confFinal, profMAx, cantMaxExplorar);

                if (resultado == null)
                {
                    solucion.agregarTexto("NO SE ENCONTRO SOLUCION DENTRO DE LOS LIMITES ESTABLECIDOS");
                } else
                {
                    solucion.agregarTexto("--------EL CAMINO A LA SOLUCION ES------------ ");
                    while (resultado.getPadre() != null)
                    {
                        solucion.imprimirSolucion(resultado.getEstado());
                        resultado = resultado.getPadre();
                    }
                    solucion.agregarTexto("Nodo inicial:");
                    for (int i = 0; i < fila; i++)
                    {
                        for (int j = 0; j < columna; j++)
                        {
                            solucion.agregarTextoMatriz("[" + confInicial[i][j] + "]");
                        }
                        solucion.agregarTexto("");
                    }
                }
//                solucion.agregarTexto("Primero el Mejor");
                break;
            case 3:
                nodoRaiz = new Nodo(confInicial);
                solucion.agregarTexto("---------Paso Por Paso----------");
                resultado = solucion.buscarSolucionAestrella(nodoRaiz, confFinal, profMAx, cantMaxExplorar);
                if (resultado == null)
                {
                    solucion.agregarTexto("NO SE ENCONTRO SOLUCION DENTRO DE LOS LIMITES ESTABLECIDOS");
                } else
                {
                    solucion.agregarTexto("--------EL CAMINO A LA SOLUCION ES------------ ");
                    while (resultado.getPadre() != null)
                    {
                        solucion.imprimirSolucion(resultado.getEstado());
                        resultado = resultado.getPadre();
                    }
                    solucion.agregarTexto("Nodo inicial:");
                    for (int i = 0; i < fila; i++)
                    {
                        for (int j = 0; j < columna; j++)
                        {
                            solucion.agregarTextoMatriz("[" + confInicial[i][j] + "]");
                        }
                        solucion.agregarTexto("");
                    }
                }
//                solucion.agregarTexto("A*");
                break;

        }


    }//GEN-LAST:event_jBtnResolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InterfazPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new InterfazPuzzle().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnReiniciar;
    private javax.swing.JButton jBtnResolver;
    private javax.swing.JComboBox<String> jCmbMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlBotones;
    private javax.swing.JPanel jPnlCF;
    private javax.swing.JPanel jPnlCI;
    private javax.swing.JPanel jPnlMetodos;
    private javax.swing.JPanel jPnlOpciones;
    private javax.swing.JPanel jPnlParam;
    private javax.swing.JPanel jPnlSolucion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCF1;
    private javax.swing.JTextField jTxtCF2;
    private javax.swing.JTextField jTxtCF3;
    private javax.swing.JTextField jTxtCF4;
    private javax.swing.JTextField jTxtCF5;
    private javax.swing.JTextField jTxtCF6;
    private javax.swing.JTextField jTxtCF7;
    private javax.swing.JTextField jTxtCF8;
    private javax.swing.JTextField jTxtCF9;
    private javax.swing.JTextField jTxtCI1;
    private javax.swing.JTextField jTxtCI2;
    private javax.swing.JTextField jTxtCI3;
    private javax.swing.JTextField jTxtCI4;
    private javax.swing.JTextField jTxtCI5;
    private javax.swing.JTextField jTxtCI6;
    private javax.swing.JTextField jTxtCI7;
    private javax.swing.JTextField jTxtCI8;
    private javax.swing.JTextField jTxtCI9;
    private javax.swing.JTextField jTxtCantMaxExplorar;
    private javax.swing.JTextField jTxtProfMax;
    private javax.swing.JTextArea jTxtSolucion;
    // End of variables declaration//GEN-END:variables

    LogicaResolucion solucion;
    javax.swing.JTextField[][] confInicialArray = new javax.swing.JTextField[3][3];
    javax.swing.JTextField[][] confFinalArray = new javax.swing.JTextField[3][3];
    private java.awt.Font fuente = new Font("SansSerif", java.awt.Font.BOLD, 20);
}
